# Generated by Django 3.1.6 on 2021-02-03 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('akiboxImpl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.CharField(default=uuid.UUID('dab9532a-65cd-11eb-9785-3e22fb0d93ba'), max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('dab93de0-65cd-11eb-9785-3e22fb0d93ba'), max_length=128, primary_key=True, serialize=False),
        ),
    ]
